### ISSUE TITLE
broken generator (?)

### ISSUE THREAD

**Issue by xerc** [MtDalPizzol/laravel-viltify#8]
```
php  @  8.01.11
npm  @  8.19.2
node @ 18.10.0
```
🚀  Invoking generators...
 ERROR  Error: Cannot find module '../presets/undefined'
        Require stack:
        - /tmp/l9viltify/resources-tmp/node_modules/vue-cli-plugin-vuetify/generator/index.js
        - /tmp/l9viltify/resources-tmp/package.json
Error: Cannot find module '../presets/undefined'
Require stack:
- /tmp/l9viltify/resources-tmp/node_modules/vue-cli-plugin-vuetify/generator/index.js
- /tmp/l9viltify/resources-tmp/package.json
    at Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at module.exports (/tmp/l9viltify/resources-tmp/node_modules/vue-cli-plugin-vuetify/generator/index.js:15:10)
    at Generator.initPlugins (/usr/local/Cellar/vue-cli/5.0.8/libexec/lib/node_modules/@vue/cli/lib/Generator.js:180:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Generator.generate (/usr/local/Cellar/vue-cli/5.0.8/libexec/lib/node_modules/@vue/cli/lib/Generator.js:198:5)
    at async Creator.create (/usr/local/Cellar/vue-cli/5.0.8/libexec/lib/node_modules/@vue/cli/lib/Creator.js:209:5)
    at async create (/usr/local/Cellar/vue-cli/5.0.8/libexec/lib/node_modules/@vue/cli/lib/create.js:72:3)
Couldn't create Vue CLI project.

**Comment by xerc** [comment]
_followed by_
copy(/tmp/l9viltify/resources/src/plugins/vuetify.js)
Failed to open stream: No such file or directory @ vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:322
